# Generated by Django 5.2.15 on 2026-09-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='admin_reply',
            field=models.TextField(blank=True, default='', help_text='Reply from support staff, shown to the user on their ticket.'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
