# Generated by Django 5.2.15 on 2026-09-09 09:27, hand-edited to backfill
# existing admin_reply text into the new message thread before dropping it.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_admin_reply_as_message(apps, schema_editor):
    SupportTicket = apps.get_model('helpdesk', 'SupportTicket')
    SupportTicketMessage = apps.get_model('helpdesk', 'SupportTicketMessage')
    for ticket in SupportTicket.objects.exclude(admin_reply='').exclude(admin_reply__isnull=True):
        # created_at is auto_now_add, so the backfilled entry is timestamped
        # "now" rather than the original reply time — acceptable for this
        # one-off historical backfill.
        SupportTicketMessage.objects.create(
            ticket=ticket,
            author=None,
            is_staff=True,
            message_type='message',
            body=ticket.admin_reply,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_supportticket_admin_reply_supportticket_replied_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField(default=False, help_text='True if this entry was posted by support staff via /admin.')),
                ('message_type', models.CharField(choices=[('message', 'Message'), ('status_change', 'Status change'), ('system', 'System')], default='message', max_length=20)),
                ('body', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='helpdesk/attachments/')),
                ('old_status', models.CharField(blank=True, default='', max_length=15)),
                ('new_status', models.CharField(blank=True, default='', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='helpdesk.supportticket')),
            ],
            options={
                'db_table': 'support_ticket_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='support_tic_ticket__506b6d_idx')],
            },
        ),
        migrations.RunPython(backfill_admin_reply_as_message, noop_reverse),
        migrations.RemoveField(
            model_name='supportticket',
            name='admin_reply',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='replied_at',
        ),
    ]
