# Generated by Django 5.0.14 on 2026-03-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_sites',
            field=models.ManyToManyField(blank=True, help_text='Sites/projects this manager has access to', related_name='assigned_managers', to='construction.site'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('accountant', 'Accountant'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
