# Generated by Django 5.0.14 on 2026-03-25 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenant_business_type'),
        ('users', '0003_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('accountant', 'Accountant'), ('viewer', 'Viewer')], max_length=20)),
                ('module', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('inventory', 'Inventory'), ('accounting', 'Accounting'), ('construction', 'Construction'), ('reports', 'Reports'), ('settings', 'Settings'), ('hr', 'HR'), ('pos', 'POS')], max_length=50)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('export', 'Export'), ('approve', 'Approve')], max_length=20)),
                ('allowed', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'role_permissions',
                'ordering': ['role', 'module', 'action'],
                'indexes': [models.Index(fields=['tenant', 'role'], name='role_permis_tenant__773d33_idx'), models.Index(fields=['tenant', 'role', 'module'], name='role_permis_tenant__d2e85c_idx')],
                'unique_together': {('tenant', 'role', 'module', 'action')},
            },
        ),
    ]
