# Generated by Django 6.0.3 on 2026-03-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_change_tenant_cascade_to_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('inventory', 'Inventory'), ('hardware', 'Hardware'), ('accounting', 'Accounting'), ('construction', 'Construction'), ('reports', 'Reports'), ('settings', 'Settings'), ('hr', 'HR'), ('pos', 'POS')], max_length=50),
        ),
    ]
