# Generated by Django 6.0.3 on 2026-03-29 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_remove_invitation_unique_constraint'),
        ('users', '0006_alter_rolepermission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('inventory', 'Inventory'), ('accounting', 'Accounting'), ('construction', 'Construction'), ('hardware', 'Hardware'), ('reports', 'Reports'), ('settings', 'Settings'), ('hr', 'HR'), ('pos', 'POS')], max_length=50),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('budget_alert', 'Budget Alert'), ('task_reminder', 'Task Reminder'), ('system_message', 'System Message'), ('user_message', 'User Message'), ('approval_request', 'Approval Request'), ('status_update', 'Status Update')], default='system_message', max_length=50)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('success', 'Success')], default='info', max_length=20)),
                ('reference_type', models.CharField(blank=True, help_text='Model name (e.g., construction_site, sales_order)', max_length=50)),
                ('reference_id', models.IntegerField(blank=True, help_text='ID of the related object', null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional notification data')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate when notification is clicked', max_length=500)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'user', '-created_at'], name='notificatio_tenant__33436d_idx'), models.Index(fields=['tenant', 'user', 'is_read'], name='notificatio_tenant__391cf9_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'), models.Index(fields=['level'], name='notificatio_level_469423_idx')],
            },
        ),
    ]
