# Generated by Django 6.0.3 on 2026-03-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_rolepermission_module_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('accountant', 'Accountant'), ('cashier', 'Cashier'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
