# Generated by Django 6.0.3 on 2026-04-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_avatar_notificationpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('sales', 'Sales'), ('purchase', 'Purchase'), ('inventory', 'Inventory'), ('accounting', 'Accounting'), ('construction', 'Construction'), ('hardware', 'Hardware'), ('reports', 'Reports'), ('settings', 'Settings'), ('hr', 'HR'), ('pos', 'POS')], max_length=50),
        ),
    ]
