# Generated by Django 6.0.3 on 2026-04-01 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_dashboard_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppearancePreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', help_text='Interface theme preference', max_length=10)),
                ('language', models.CharField(choices=[('en-US', 'English (US)'), ('en-GB', 'English (UK)'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('hi', 'Hindi')], default='en-US', help_text='Preferred language', max_length=10)),
                ('timezone', models.CharField(choices=[('UTC', 'UTC (GMT+0:00)'), ('America/New_York', 'Eastern Time (GMT-5:00)'), ('America/Chicago', 'Central Time (GMT-6:00)'), ('America/Denver', 'Mountain Time (GMT-7:00)'), ('America/Los_Angeles', 'Pacific Time (GMT-8:00)'), ('Europe/London', 'London (GMT+0:00)'), ('Europe/Paris', 'Paris (GMT+1:00)'), ('Asia/Dubai', 'Dubai (GMT+4:00)'), ('Asia/Kolkata', 'IST (GMT+5:30)'), ('Asia/Singapore', 'Singapore (GMT+8:00)'), ('Asia/Tokyo', 'Tokyo (GMT+9:00)'), ('Australia/Sydney', 'Sydney (GMT+10:00)')], default='UTC', help_text='Preferred timezone', max_length=50)),
                ('compact_mode', models.BooleanField(default=False, help_text='Enable compact display mode')),
                ('smooth_animations', models.BooleanField(default=True, help_text='Enable smooth animations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appearance_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appearance Preference',
                'verbose_name_plural': 'Appearance Preferences',
                'db_table': 'user_appearance_preferences',
            },
        ),
    ]
