# Generated by Django 5.0.14 on 2026-07-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rolepermission_hr_configure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.AlterField(
            model_name='appearancepreferences',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC (GMT+0:00)'), ('Asia/Kathmandu', 'Nepal Time (GMT+5:45)'), ('America/New_York', 'Eastern Time (GMT-5:00)'), ('America/Chicago', 'Central Time (GMT-6:00)'), ('America/Denver', 'Mountain Time (GMT-7:00)'), ('America/Los_Angeles', 'Pacific Time (GMT-8:00)'), ('Europe/London', 'London (GMT+0:00)'), ('Europe/Paris', 'Paris (GMT+1:00)'), ('Asia/Dubai', 'Dubai (GMT+4:00)'), ('Asia/Kolkata', 'IST (GMT+5:30)'), ('Asia/Singapore', 'Singapore (GMT+8:00)'), ('Asia/Tokyo', 'Tokyo (GMT+9:00)'), ('Australia/Sydney', 'Sydney (GMT+10:00)')], default='UTC', help_text='Preferred timezone', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('budget_alert', 'Budget Alert'), ('task_reminder', 'Task Reminder'), ('system_message', 'System Message'), ('user_message', 'User Message'), ('approval_request', 'Approval Request'), ('status_update', 'Status Update'), ('inventory_alert', 'Inventory Alert'), ('payment_reminder', 'Payment Reminder'), ('sales_alert', 'Sales Alert'), ('purchase_reminder', 'Purchase Reminder')], default='system_message', max_length=50),
        ),
        migrations.DeleteModel(
            name='PrivacyPreferences',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
