# Generated by Django 5.0.14 on 2026-08-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearancepreferences',
            name='navbar_position',
            field=models.CharField(choices=[('left', 'Left'), ('top', 'Top')], default='left', help_text='App bar position (left or top)', max_length=10),
        ),
    ]
