# Generated by Django 5.2.15 on 2026-09-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_appearancepreferences_navbar_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearancepreferences',
            name='accent_color',
            field=models.CharField(blank=True, help_text='Custom accent color (hex code, e.g., #3B82F6)', max_length=7, null=True),
        ),
    ]
