# Generated by Django 5.2.15 on 2026-09-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_add_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearancepreferences',
            name='navbar_color',
            field=models.CharField(blank=True, help_text='Custom navbar/icon-rail background color (hex code, e.g., #1E2A3B)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='appearancepreferences',
            name='sidebar_color',
            field=models.CharField(blank=True, help_text='Custom sidebar background color (hex code, e.g., #1E2A3B)', max_length=7, null=True),
        ),
    ]
