# Generated by Django 5.2.15 on 2026-09-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_appearancepreferences_navbar_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearancepreferences',
            name='border_radius',
            field=models.CharField(blank=True, help_text='Custom global border radius (CSS length, e.g. 0.625rem)', max_length=20, null=True),
        ),
    ]
