# Generated by Django 5.2.15 on 2026-09-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_appearancepreferences_border_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearancepreferences',
            name='high_contrast',
            field=models.BooleanField(default=False, help_text='Boost border/text contrast for low-vision accessibility'),
        ),
    ]
