# Generated by Django 5.2.15 on 2026-09-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_appearancepreferences_high_contrast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('import', 'Import'), ('post', 'Post'), ('reverse', 'Reverse'), ('copy', 'Copy'), ('close', 'Close'), ('approve', 'Approve'), ('reject', 'Reject'), ('refund', 'Refund'), ('adjust', 'Adjust')], max_length=20),
        ),
    ]
