# Generated by Django 5.2.15 on 2026-09-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearancepreferences',
            name='accent_color',
            field=models.CharField(blank=True, default='#8B5CF6', help_text='Custom accent color (hex code, e.g., #3B82F6)', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='appearancepreferences',
            name='border_radius',
            field=models.CharField(blank=True, default='1.5rem', help_text='Custom global border radius (CSS length, e.g. 0.625rem)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appearancepreferences',
            name='sidebar_color',
            field=models.CharField(blank=True, default='#0F172A', help_text='Custom sidebar background color (hex code, e.g., #1E2A3B)', max_length=7, null=True),
        ),
    ]
