# Generated by Django 5.2.15 on 2026-09-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_appearancepreferences_accent_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearancepreferences',
            name='border_radius',
            field=models.CharField(blank=True, default='1rem', help_text='Custom global border radius (CSS length, e.g. 0.625rem)', max_length=20, null=True),
        ),
    ]
