# Generated by Django 5.2.15 on 2026-09-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_appearancepreferences_border_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearancepreferences',
            name='navbar_position',
            field=models.CharField(choices=[('left', 'Left'), ('top', 'Top')], default='top', help_text='App bar position (left or top)', max_length=10),
        ),
    ]
