# Generated by Django 5.0.14 on 2026-07-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsewaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Enable eSewa payments for subscription billing')),
                ('use_sandbox', models.BooleanField(default=True, help_text='Use eSewa test/sandbox environment (disable for live payments)')),
                ('product_code', models.CharField(blank=True, help_text='Merchant product code from eSewa (e.g. EPAYTEST for sandbox)', max_length=100)),
                ('secret_key', models.CharField(blank=True, help_text='eSewa HMAC secret key — keep confidential', max_length=255)),
                ('frontend_url', models.URLField(blank=True, help_text='Customer app URL for payment callbacks (e.g. http://localhost:3000)')),
                ('payment_url', models.URLField(blank=True, help_text='Optional override for eSewa payment form URL')),
                ('status_url', models.URLField(blank=True, help_text='Optional override for eSewa transaction status API URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'eSewa integration',
                'verbose_name_plural': 'eSewa integration',
                'db_table': 'billing_esewa_settings',
            },
        ),
    ]
