# Generated by Django 5.0.14 on 2026-07-03 07:45

from django.db import migrations, models


def backfill_callback_urls(apps, schema_editor):
    EsewaSettings = apps.get_model('billing', 'EsewaSettings')
    for obj in EsewaSettings.objects.all():
        base = (obj.frontend_url or 'http://localhost:3000').rstrip('/')
        changed = False
        if not obj.success_url:
            obj.success_url = f'{base}/dashboard/settings/billing/success'
            changed = True
        if not obj.failure_url:
            obj.failure_url = f'{base}/dashboard/settings/billing/failure'
            changed = True
        if changed:
            obj.save(update_fields=['success_url', 'failure_url'])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_esewasettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='esewasettings',
            name='failure_url',
            field=models.URLField(blank=True, help_text='Where eSewa redirects after failed/cancelled payment. Leave blank to auto-use {frontend}/dashboard/settings/billing/failure'),
        ),
        migrations.AddField(
            model_name='esewasettings',
            name='success_url',
            field=models.URLField(blank=True, help_text='Where eSewa redirects after successful payment. Leave blank to auto-use {frontend}/dashboard/settings/billing/success'),
        ),
        migrations.AlterField(
            model_name='esewasettings',
            name='frontend_url',
            field=models.URLField(blank=True, help_text='Customer app base URL (e.g. http://localhost:3000)'),
        ),
        migrations.AlterField(
            model_name='esewasettings',
            name='payment_url',
            field=models.URLField(blank=True, help_text='eSewa payment form POST URL. Leave blank for sandbox/production default.'),
        ),
        migrations.AlterField(
            model_name='esewasettings',
            name='status_url',
            field=models.URLField(blank=True, help_text='eSewa transaction verification API URL. Leave blank for sandbox/production default.'),
        ),
        migrations.RunPython(backfill_callback_urls, migrations.RunPython.noop),
    ]
