# Generated by Django 5.0.14 on 2026-07-07 07:05

from decimal import Decimal
from django.db import migrations, models


def seed_subscription_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('billing', 'SubscriptionPlan')
    plans = [
        {
            'code': 'free',
            'name': 'Free',
            'plan_type': 'free',
            'price': Decimal('0.00'),
            'max_users': 1,
            'features': ['1 user', 'Sales & Purchase', 'Inventory', 'Basic Reports'],
            'modules': ['sales', 'purchase', 'inventory', 'reports'],
            'is_popular': False,
            'sort_order': 0,
        },
        {
            'code': 'starter',
            'name': 'Starter',
            'plan_type': 'basic',
            'price': Decimal('999.00'),
            'max_users': 2,
            'features': ['Up to 2 users', 'Sales & Purchase', 'Basic Reports', 'Email Support'],
            'modules': ['sales', 'purchase', 'inventory', 'reports'],
            'is_popular': False,
            'sort_order': 1,
        },
        {
            'code': 'business',
            'name': 'Business',
            'plan_type': 'premium',
            'price': Decimal('2499.00'),
            'max_users': 10,
            'features': [
                'Up to 10 users', 'All Modules', 'Advanced Reports',
                'Priority Support', 'API Access',
            ],
            'modules': ['sales', 'purchase', 'inventory', 'accounting', 'reports', 'pos', 'hr'],
            'is_popular': True,
            'sort_order': 2,
        },
        {
            'code': 'enterprise',
            'name': 'Enterprise',
            'plan_type': 'enterprise',
            'price': Decimal('5999.00'),
            'max_users': None,
            'features': [
                'Unlimited users', 'All Modules', 'Custom Reports',
                'Dedicated Support', 'Custom Integrations', 'SLA Guarantee',
            ],
            'modules': [
                'sales', 'purchase', 'inventory', 'accounting',
                'reports', 'pos', 'hr', 'construction',
            ],
            'is_popular': False,
            'sort_order': 3,
        },
    ]
    for plan in plans:
        SubscriptionPlan.objects.update_or_create(code=plan['code'], defaults=plan)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_esewasettings_failure_url_esewasettings_success_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable plan identifier used in checkout (e.g. starter, business)', max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], help_text='Maps to tenant.plan_type when a user subscribes', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly price in NPR (0 = free)', max_digits=12)),
                ('max_users', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited users', null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='Bullet points shown on the billing page')),
                ('modules', models.JSONField(blank=True, default=list, help_text='Modules enabled for organizations on this plan')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive plans are hidden from /settings/billing')),
                ('is_popular', models.BooleanField(default=False, help_text='Highlights this plan as "Most popular" in the customer app')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription plan',
                'verbose_name_plural': 'Subscription plans',
                'db_table': 'billing_subscription_plans',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.RunPython(seed_subscription_plans, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='esewasettings',
            name='failure_url',
            field=models.URLField(blank=True, help_text='Where eSewa redirects after failed/cancelled payment. Leave blank to auto-use {frontend}/settings/billing/failure'),
        ),
        migrations.AlterField(
            model_name='esewasettings',
            name='success_url',
            field=models.URLField(blank=True, help_text='Where eSewa redirects after successful payment. Leave blank to auto-use {frontend}/settings/billing/success'),
        ),
    ]
