# Generated by Django 5.0.14 on 2026-08-18 13:30

from django.db import migrations


def add_personal_finance_to_plans(apps, schema_editor):
    """Add personal_finance module to all subscription plans."""
    SubscriptionPlan = apps.get_model('billing', 'SubscriptionPlan')
    
    for plan in SubscriptionPlan.objects.all():
        if 'personal_finance' not in plan.modules:
            # Add personal_finance as the first module for better visibility
            plan.modules = ['personal_finance'] + plan.modules
            plan.save(update_fields=['modules'])
            
        # Also update features list to mention Personal Finance for free plan
        if plan.code == 'free' and 'Personal Finance' not in plan.features:
            plan.features = ['Personal Finance'] + plan.features
            plan.save(update_fields=['features'])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_business_plan_all_modules'),
    ]

    operations = [
        migrations.RunPython(add_personal_finance_to_plans, migrations.RunPython.noop),
    ]
