# Generated by Django 5.0.14 on 2026-08-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeaccount',
            name='account_number',
            field=models.CharField(blank=True, help_text='Account/card number', max_length=50),
        ),
        migrations.AddField(
            model_name='financeaccount',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name for bank accounts', max_length=255),
        ),
    ]
