# Generated by Django 5.0.14 on 2026-08-19 12:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financeaccount_account_number_and_more'),
        ('tenants', '0017_merge_20260818_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('in', 'Money In (Received)'), ('out', 'Money Out (Given)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField()),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('esewa', 'eSewa'), ('bank', 'Bank Transfer')], help_text='Payment method (only for Money Out transactions)', max_length=20, null=True)),
                ('receipt', models.FileField(blank=True, help_text='Receipt image or PDF (only for Money Out transactions)', null=True, upload_to='finance/party-receipts/')),
                ('note', models.TextField(blank=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.partylender')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Party Transaction',
                'verbose_name_plural': 'Party Transactions',
                'db_table': 'finance_party_transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyTransactionShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_type', models.CharField(choices=[('transaction', 'Single Transaction'), ('party_ledger', 'Party Ledger')], max_length=20)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('party', models.ForeignKey(blank=True, help_text='For party ledger shares', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_shares', to='finance.partylender')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('transaction', models.ForeignKey(blank=True, help_text='For single transaction shares', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='finance.partytransaction')),
            ],
            options={
                'verbose_name': 'Party Transaction Share',
                'verbose_name_plural': 'Party Transaction Shares',
                'db_table': 'finance_party_transaction_shares',
                'ordering': ['-created_at'],
            },
        ),
    ]
