# Generated by Django 5.0.14 on 2026-08-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_add_party_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='partytransaction',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, help_text='Unique token for sharing this transaction', max_length=64, null=True, unique=True),
        ),
    ]
