# Generated by Django 5.0.14 on 2026-08-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_add_share_token_to_party_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='partylender',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, help_text='Unique token for sharing this party ledger', max_length=64, null=True, unique=True),
        ),
    ]
