# Generated by Django 5.0.14 on 2026-08-21 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_backfill_party_share_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financebill',
            name='bill_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='financebill',
            name='recurring',
            field=models.CharField(blank=True, choices=[('one-time', 'One-time'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='one-time', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.financeaccount'),
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
