# Generated by Django 5.0.1 on 2026-08-31 11:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_make_fields_optional_for_kirana'),
        ('tenants', '0021_remove_business_type_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('home', 'Home Loan'), ('car', 'Car Loan'), ('personal', 'Personal Loan'), ('education', 'Education Loan')], default='personal', max_length=20)),
                ('principal', models.DecimalField(decimal_places=2, help_text='Original loan amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('emi', models.DecimalField(decimal_places=2, help_text='Monthly EMI amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('remaining_balance', models.DecimalField(decimal_places=2, help_text='Current remaining balance', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('start_date', models.DateField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Finance Loan',
                'verbose_name_plural': 'Finance Loans',
                'db_table': 'finance_loans',
                'ordering': ['-start_date'],
            },
        ),
    ]
