# Generated by Django 5.2.15 on 2026-09-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_financeloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='financecategory',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Pre-defined category that cannot be edited or deleted'),
        ),
    ]
