# Generated by Django 5.2.15 on 2026-09-06 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_financecategory_is_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partytransaction',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.partylender'),
        ),
    ]
