# Generated by Django 5.0.14 on 2026-03-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='created_from_registration',
            field=models.BooleanField(default=False, help_text='True if tenant was created during user registration, False if created explicitly from /erp/new'),
        ),
    ]
