# Generated by Django 5.0.14 on 2026-03-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_created_from_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(choices=[('construction', 'Construction'), ('hardware', 'Hardware'), ('retail', 'Retail'), ('wholesale', 'Wholesale'), ('manufacturing', 'Manufacturing'), ('services', 'Services'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
