# Generated by Django 5.0.14 on 2026-03-27 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenant_business_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('accountant', 'Accountant'), ('viewer', 'Viewer')], default='viewer', help_text='Role to assign when invitation is accepted', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message from inviter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Invitation expiry date')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When user accepted/declined', null=True)),
                ('invited_by', models.ForeignKey(help_text='User who sent the invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(help_text='User being invited', on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'organization_invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invited_user', 'status'], name='organizatio_invited_ef0434_idx'), models.Index(fields=['tenant', 'status'], name='organizatio_tenant__cb8109_idx'), models.Index(fields=['-created_at'], name='organizatio_created_9a587c_idx')],
                'unique_together': {('tenant', 'invited_user', 'status')},
            },
        ),
    ]
