# Generated by Django 5.0.14 on 2026-03-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_usertenantmembership'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationinvitation',
            unique_together=set(),
        ),
    ]
