# Generated by Django 6.0.3 on 2026-03-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_remove_invitation_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='accounting_start_date',
            field=models.DateField(blank=True, help_text='Date when accounting records start for this organization', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Organization logo', null=True, upload_to='tenant_logos/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vat_registered',
            field=models.BooleanField(default=False, help_text='Whether the organization is registered for VAT'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='workspace_name',
            field=models.CharField(blank=True, help_text='Custom workspace name (defaults to organization name if not provided)', max_length=255),
        ),
    ]
