# Generated by Django 6.0.3 on 2026-03-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_accounting_start_date_tenant_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinvitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('accountant', 'Accountant'), ('cashier', 'Cashier'), ('viewer', 'Viewer')], default='viewer', help_text='Role to assign when invitation is accepted', max_length=20),
        ),
    ]
