# Generated by Django 5.0.14 on 2026-07-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_pan_vat_number_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertenantmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('accountant', 'Accountant'), ('cashier', 'Cashier'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
