# Generated by Django 5.0.14 on 2026-07-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_usertenantmembership_is_active'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organizationinvitation',
            new_name='organizatio_invited_f28a67_idx',
            old_name='organizatio_invited_8f2a1c_idx',
        ),
    ]
