# Generated by Django 5.0.14 on 2026-08-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_rename_organizatio_invited_8f2a1c_idx_organizatio_invited_f28a67_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(choices=[('construction', 'Construction'), ('hardware', 'Hardware'), ('retail', 'Retail'), ('wholesale', 'Wholesale'), ('manufacturing', 'Manufacturing'), ('services', 'Services'), ('personal', 'Personal Finance'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
