# Generated by Django 5.0.14 on 2026-08-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_rename_organizatio_invited_8f2a1c_idx_organizatio_invited_f28a67_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='account_type',
            field=models.CharField(choices=[('organization', 'Organization'), ('personal', 'Personal')], default='organization', help_text='Personal accounts are limited to the personal finance module', max_length=20),
        ),
    ]
