# Generated by Django 5.0.14 on 2026-08-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_alter_tenant_business_type'),
        ('tenants', '0016_tenant_account_type'),
    ]

    operations = [
    ]
