# Generated by Django 5.0.14 on 2026-08-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_merge_20260818_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(choices=[('construction', 'Construction'), ('hardware', 'Hardware'), ('retail', 'Retail'), ('kirana', 'Small Retail / Kirana'), ('wholesale', 'Wholesale'), ('manufacturing', 'Manufacturing'), ('services', 'Services'), ('personal', 'Personal Finance'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
