# Generated by Django 5.0.14 on 2026-08-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_alter_tenant_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='account_type',
            field=models.CharField(choices=[('organization', 'Organization'), ('personal', 'Personal'), ('retail', 'Retail / Kirana'), ('construction', 'Construction'), ('hardware', 'Hardware')], default='organization', help_text='Personal accounts are limited to the personal finance module', max_length=20),
        ),
    ]
