# Generated by Django 5.0.14 on 2026-08-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0020_remove_name_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
