# Generated by Django 5.0.14 on 2026-09-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_add_pos_to_missing_kirana_retail_tenants'),
        ('tenants', '0021_remove_business_type_choices'),
    ]

    operations = [
    ]
