# Generated by Django 5.0.14 on 2026-09-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0022_merge_20260906_1407'),
        ('tenants', '0022_merge_20260906_1554'),
    ]

    operations = [
    ]
