# Generated by Django 5.2.15 on 2026-09-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0022_merge_20260906_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Workplace', 'verbose_name_plural': 'Workplaces'},
        ),
        migrations.AddField(
            model_name='tenant',
            name='disabled_features',
            field=models.JSONField(blank=True, default=list, help_text="Sidebar sub-feature hrefs turned off within an active module, e.g. ['/dashboard/sales/credit-notes']"),
        ),
    ]
