# Generated by Django 5.0.14 on 2026-09-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0023_merge_20260911_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='disabled_features',
            field=models.JSONField(blank=True, default=list, help_text="Sidebar sub-feature hrefs turned off within an active module, e.g. ['/dashboard/sales/credit-notes']"),
        ),
    ]
