# Generated by Django 5.0.1 on 2026-08-31 18:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0009_make_sku_optional'),
        ('sales', '0009_make_fields_optional_for_kirana'),
        ('tenants', '0021_remove_business_type_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_number', models.CharField(help_text='Vehicle registration number (e.g., BA 1 KHA 1234)', max_length=20)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('pickup', 'Pickup'), ('tempo', 'Tempo'), ('van', 'Van'), ('other', 'Other')], default='truck', max_length=20)),
                ('capacity_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Load capacity in kilograms', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_delivery', 'On Delivery'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='available', max_length=20)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_due', models.DateField(blank=True, null=True)),
                ('is_owned', models.BooleanField(default=True, help_text='True if owned by company, False if rented/hired')),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hardware_vehicles',
                'ordering': ['vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_number', models.CharField(help_text='Unique delivery tracking number', max_length=50, unique=True)),
                ('challan_number', models.CharField(blank=True, help_text='Delivery challan number', max_length=50)),
                ('delivery_address', models.TextField(help_text='Full delivery address including landmarks')),
                ('customer_contact_name', models.CharField(blank=True, help_text='Contact person at delivery site', max_length=255)),
                ('customer_contact_phone', models.CharField(blank=True, help_text='Phone number at delivery site', max_length=20)),
                ('scheduled_date', models.DateField(help_text='Date when delivery is scheduled')),
                ('scheduled_time', models.TimeField(blank=True, help_text='Approximate delivery time', null=True)),
                ('loading_started_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_time', models.DateTimeField(blank=True, help_text='Time when vehicle left for delivery', null=True)),
                ('delivery_completed_at', models.DateTimeField(blank=True, help_text='Time when delivery was completed', null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('loaded', 'Loaded on Vehicle'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('partial', 'Partially Delivered'), ('failed', 'Failed Delivery'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transport_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transport/freight charge for this delivery', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('loading_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Loading/unloading labour charge', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('delivery_notes', models.TextField(blank=True, help_text='Special instructions or notes for delivery')),
                ('driver_notes', models.TextField(blank=True, help_text='Notes added by driver during delivery')),
                ('customer_signature', models.ImageField(blank=True, help_text='Customer signature on delivery challan', null=True, upload_to='hardware/delivery_signatures/%Y/%m/')),
                ('delivery_photos', models.JSONField(blank=True, default=list, help_text='Photos of delivered materials (list of URLs)')),
                ('failure_reason', models.TextField(blank=True, help_text='Reason if delivery failed')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deliveries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hardware_deliveries', to='sales.customer')),
                ('invoice', models.ForeignKey(help_text='Invoice for which materials are being delivered', on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='sales.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='hardware.vehicle')),
            ],
            options={
                'db_table': 'hardware_deliveries',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_quantity', models.DecimalField(decimal_places=2, help_text='Quantity as per invoice', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('delivered_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual quantity delivered', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('damaged_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity damaged during transit', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price from invoice', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Notes about this item in delivery')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hardware.delivery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hardware_delivery_items',
                'ordering': ['delivery', 'product__name'],
                'indexes': [models.Index(fields=['tenant', 'delivery'], name='hardware_de_tenant__d5e1f8_idx'), models.Index(fields=['tenant', 'product'], name='hardware_de_tenant__b41def_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['tenant', 'status'], name='hardware_ve_tenant__8158d3_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['tenant', 'vehicle_number'], name='hardware_ve_tenant__4ca543_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('tenant', 'vehicle_number')},
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['tenant', 'status'], name='hardware_de_tenant__1e3f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['tenant', 'customer'], name='hardware_de_tenant__b68c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['tenant', 'invoice'], name='hardware_de_tenant__b74d73_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['tenant', 'scheduled_date'], name='hardware_de_tenant__202718_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivery_number'], name='hardware_de_deliver_c95fc7_idx'),
        ),
    ]
