# Generated by Django 5.2.15 on 2026-09-03 11:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
        ('inventory', '0009_make_sku_optional'),
        ('tenants', '0022_merge_20260906_1247'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Rate for this product as of effective_date', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_label', models.CharField(blank=True, help_text='Display unit for the rate, e.g. "per kg", "per bori" (defaults to the product unit)', max_length=50)),
                ('effective_date', models.DateField(help_text='Date this rate applies from')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_rates_posted', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hardware_material_rates',
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'product', '-effective_date'], name='hardware_ma_tenant__28071c_idx')],
            },
        ),
    ]
