# Generated by Django 5.2.15 on 2026-09-06 09:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_materialrate'),
        ('sales', '0010_add_payment_method_ref'),
        ('tenants', '0022_merge_20260906_1247'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. "Cement Mixer", "Drill Machine"', max_length=255)),
                ('category', models.CharField(choices=[('power_tool', 'Power Tool'), ('machinery', 'Machinery'), ('scaffolding', 'Scaffolding'), ('measuring', 'Measuring Equipment'), ('other', 'Other')], default='other', max_length=20)),
                ('total_units', models.PositiveIntegerField(default=1, help_text='How many of this item the shop owns')),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Default rent charged per day per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default refundable security deposit per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True, help_text='Turn off to hide from "new rental" without deleting rental history')),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hardware_rental_equipment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Rate at the time of rental (may differ from current equipment default)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('deposit_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('checkout_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(help_text='Expected return date')),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Rented Out'), ('returned', 'Returned'), ('damaged', 'Returned Damaged'), ('lost', 'Lost / Not Returned')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_rentals_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hardware_rentals', to='sales.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='hardware.rentalequipment')),
            ],
            options={
                'db_table': 'hardware_rentals',
                'ordering': ['-checkout_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rentalequipment',
            index=models.Index(fields=['tenant', 'category'], name='hardware_re_tenant__391440_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['tenant', 'status'], name='hardware_re_tenant__09934a_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['tenant', 'due_date'], name='hardware_re_tenant__f3b84a_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['tenant', 'customer'], name='hardware_re_tenant__16fdc4_idx'),
        ),
    ]
