# Generated by Django 6.0.3 on 2026-03-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_bulkpricing'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bulkpricing',
            new_name='bulk_pricin_product_970117_idx',
            old_name='bulk_pricin_product_idx',
        ),
        migrations.RenameIndex(
            model_name='bulkpricing',
            new_name='bulk_pricin_tenant__f78438_idx',
            old_name='bulk_pricin_tenant_idx',
        ),
    ]
