# Generated by Django 6.0.3 on 2026-03-29 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_bulk_pricin_product_idx_bulk_pricin_product_970117_idx_and_more'),
        ('sales', '0006_alter_salesorder_order_number_and_more'),
        ('tenants', '0007_remove_invitation_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSpecificPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Special price per unit for this customer', max_digits=12)),
                ('min_quantity', models.DecimalField(decimal_places=2, default=1, help_text='Minimum quantity required (default: 1)', max_digits=10)),
                ('valid_from', models.DateField(help_text='Date from which this price is valid')),
                ('valid_until', models.DateField(blank=True, help_text='Date until which this price is valid (null = no expiry)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text="Reason for special pricing (e.g., 'Loyal customer discount', 'Negotiated rate')")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_prices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_prices', to='sales.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_prices', to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'customer_specific_prices',
                'ordering': ['customer', 'product'],
                'indexes': [models.Index(fields=['customer', 'product'], name='customer_sp_custome_1c9efe_idx'), models.Index(fields=['tenant', 'customer'], name='customer_sp_tenant__bb9444_idx'), models.Index(fields=['valid_from', 'valid_until'], name='customer_sp_valid_f_cc8bc0_idx')],
                'unique_together': {('tenant', 'customer', 'product')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('old_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('change_type', models.CharField(choices=[('cost_price', 'Cost Price Change'), ('selling_price', 'Selling Price Change'), ('both', 'Both Prices Changed')], max_length=50)),
                ('change_reason', models.TextField(blank=True, help_text="Reason for price change (e.g., 'Supplier price increase', 'Promotional discount')")),
                ('cost_price_change_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage change in cost price', max_digits=7, null=True)),
                ('selling_price_change_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage change in selling price', max_digits=7, null=True)),
                ('effective_date', models.DateField(help_text='Date when this price change becomes effective')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'price_history',
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [models.Index(fields=['product', '-effective_date'], name='price_histo_product_5261e4_idx'), models.Index(fields=['tenant', 'product'], name='price_histo_tenant__bf8466_idx'), models.Index(fields=['effective_date'], name='price_histo_effecti_4ec09b_idx')],
            },
        ),
    ]
