# Generated by Django 5.0.14 on 2026-03-25 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_tenant_created_from_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('table', 'Table'), ('chart', 'Chart'), ('both', 'Both')], default='table', max_length=20)),
                ('module', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('inventory', 'Inventory'), ('accounting', 'Accounting'), ('hr', 'HR'), ('pos', 'POS')], max_length=50)),
                ('fields', models.JSONField(default=list, help_text='Selected fields for the report')),
                ('filters', models.JSONField(default=list, help_text='Filter conditions')),
                ('grouping', models.JSONField(default=dict, help_text='Grouping configuration')),
                ('sorting', models.JSONField(default=dict, help_text='Sorting configuration')),
                ('chart_config', models.JSONField(default=dict, help_text='Chart configuration')),
                ('schedule', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'custom_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'module'], name='custom_repo_tenant__bde185_idx'), models.Index(fields=['tenant', 'created_by'], name='custom_repo_tenant__6cf705_idx')],
            },
        ),
    ]
