# Generated by Django 5.0.14 on 2026-07-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customreport',
            name='module',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('inventory', 'Inventory'), ('accounting', 'Accounting'), ('hr', 'HR'), ('pos', 'POS'), ('construction', 'Construction'), ('hardware', 'Hardware')], max_length=50),
        ),
    ]
