# Generated by Django 6.0.3 on 2026-03-31 12:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_customerspecificprice_pricehistory'),
        ('pos', '0001_initial'),
        ('tenants', '0008_tenant_accounting_start_date_tenant_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_number', models.CharField(max_length=50, unique=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, help_text='Cash in drawer at session start', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Actual cash counted at session end', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, help_text='Expected cash (opening + cash sales)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cash_variance', models.DecimalField(decimal_places=2, default=0, help_text='Difference between expected and actual (can be negative)', max_digits=12)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('upi_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('credit_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sessions', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'pos_sessions',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='postransaction',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='pos.possession'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['tenant', 'cashier', 'opened_at'], name='pos_session_tenant__6ec320_idx'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['tenant', 'status'], name='pos_session_tenant__72b97c_idx'),
        ),
    ]
