# Generated by Django 5.0.14 on 2026-08-31 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_add_payment_method_model'),
        ('pos', '0007_loyalty_refund_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='payment_method_ref',
            field=models.ForeignKey(blank=True, help_text='Reference to configured PaymentMethod (preferred over CharField)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_transactions', to='accounting.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='postransaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Fully Refunded'), ('cancelled', 'Cancelled')], default='completed', max_length=20),
        ),
    ]
