# Generated by Django 5.0.14 on 2026-08-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_loyalty_refund_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postransaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Fully Refunded'), ('cancelled', 'Cancelled')], default='completed', max_length=20),
        ),
    ]
