# Generated by Django 5.0.14 on 2026-09-03 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_make_gl_account_nullable'),
        ('pos', '0008_add_payment_method_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Bank account for non-cash payments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_transactions', to='accounting.bankaccount'),
        ),
    ]
