# Generated by Django 5.0.1 on 2026-08-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_add_payment_qr_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='possettings',
            name='esewa_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='possettings',
            name='khalti_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='possettings',
            name='fonepay_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postransaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Fully Refunded'), ('cancelled', 'Cancelled')], default='completed', max_length=20),
        ),
    ]
