# Generated by Django 5.0.1 on 2026-08-30 16:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_add_bank_qr_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possettings',
            name='bank_qr',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qr_codes'),
        ),
        migrations.AlterField(
            model_name='possettings',
            name='esewa_qr',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qr_codes'),
        ),
        migrations.AlterField(
            model_name='possettings',
            name='fonepay_qr',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qr_codes'),
        ),
        migrations.AlterField(
            model_name='possettings',
            name='khalti_qr',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qr_codes'),
        ),
    ]
