# Generated by Django 5.0.1 on 2026-08-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_alter_possettings_bank_qr_alter_possettings_esewa_qr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possettings',
            name='bank_qr',
            field=models.ImageField(blank=True, null=True, upload_to='pos/qr/'),
        ),
        migrations.AlterField(
            model_name='possettings',
            name='esewa_qr',
            field=models.ImageField(blank=True, null=True, upload_to='pos/qr/'),
        ),
        migrations.AlterField(
            model_name='possettings',
            name='fonepay_qr',
            field=models.ImageField(blank=True, null=True, upload_to='pos/qr/'),
        ),
        migrations.AlterField(
            model_name='possettings',
            name='khalti_qr',
            field=models.ImageField(blank=True, null=True, upload_to='pos/qr/'),
        ),
    ]
