# Generated by Django 5.2.15 on 2026-09-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_postransaction_bank_account'),
        ('pos', '0014_alter_possettings_bank_qr_alter_possettings_esewa_qr_and_more'),
    ]

    operations = [
    ]
