# Generated by Django 5.0.14 on 2026-09-09 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_add_digital_wallets_to_bank_account'),
        ('pos', '0015_merge_20260906_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='possettings',
            name='linked_bank_account',
            field=models.ForeignKey(blank=True, help_text='Link to the bank account in Accounting → Bank Accounts that will receive bank transfer payments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_settings', to='accounting.bankaccount'),
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('fonepay', 'Fonepay'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Credit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='posrefund',
            name='refund_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('fonepay', 'Fonepay'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Credit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='postransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('fonepay', 'Fonepay'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Credit')], max_length=20),
        ),
    ]
