# Generated by Django 5.0.14 on 2026-09-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_merge_20260906_1406'),
        ('pos', '0016_add_linked_bank_account_to_pos_settings'),
    ]

    operations = [
    ]
