# Generated by Django 5.0.1 on 2026-08-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cloudinary_api_key',
            field=models.CharField(blank=True, help_text='Your Cloudinary API key', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cloudinary_api_secret',
            field=models.CharField(blank=True, help_text='Your Cloudinary API secret (stored securely)', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cloudinary_cloud_name',
            field=models.CharField(blank=True, help_text='Your Cloudinary cloud name', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='use_cloudinary',
            field=models.BooleanField(default=False, help_text='Enable Cloudinary for image storage (cloud-based CDN)'),
        ),
    ]
