# Generated by Django 5.0.14 on 2026-07-03 07:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='KHATA', max_length=255)),
                ('logo_url', models.URLField(blank=True, help_text='Public URL to logo image (recommended 180×48 PNG)')),
                ('primary_color', models.CharField(default='#22C55E', max_length=7)),
                ('secondary_color', models.CharField(default='#111827', max_length=7)),
                ('footer_text', models.TextField(blank=True, default='© KHATA Business OS. All rights reserved.')),
                ('unsubscribe_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('marketing_emails_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email branding',
                'verbose_name_plural': 'Email branding',
                'db_table': 'mail_branding',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('invitation', 'Invitation'), ('welcome', 'Welcome / Registration'), ('verification', 'Email Verification'), ('acceptance', 'Invitation Accepted'), ('marketing', 'Marketing'), ('transactional', 'Transactional'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField(help_text='HTML with variables: {{first_name}}, {{invitation_link}}, etc.')),
                ('text_body', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System templates cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mail_templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SmtpSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password_encrypted', models.TextField(blank=True)),
                ('sender_name', models.CharField(default='KHATA', max_length=255)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('reply_to_email', models.EmailField(blank=True, max_length=254)),
                ('encryption', models.CharField(choices=[('starttls', 'STARTTLS'), ('ssl', 'SSL/TLS'), ('none', 'None')], default='starttls', max_length=20)),
                ('connection_timeout', models.PositiveIntegerField(default=30, help_text='Seconds')),
                ('queue_enabled', models.BooleanField(default=True)),
                ('retry_failed', models.BooleanField(default=True)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60)),
                ('default_signature', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP settings',
                'verbose_name_plural': 'SMTP settings',
                'db_table': 'mail_smtp_settings',
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('segment', models.CharField(choices=[('all_users', 'All users'), ('tenant_admins', 'Organization admins'), ('tenant_managers', 'Managers'), ('active_tenants', 'Active organizations'), ('custom', 'Custom email list')], default='all_users', max_length=30)),
                ('custom_recipients', models.TextField(blank=True, help_text='Comma-separated emails when segment is Custom')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('subject_override', models.CharField(blank=True, max_length=255)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='mail.emailtemplate')),
            ],
            options={
                'db_table': 'mail_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField()),
                ('text_body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('paused', 'Paused')], default='queued', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=5)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.emailtemplate')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.marketingcampaign')),
            ],
            options={
                'db_table': 'mail_queue',
                'ordering': ['priority', 'scheduled_for'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='mail_queue_status_1c78a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.UUIDField(editable=False, unique=True)),
                ('to_email', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('template_slug', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('unsubscribed', 'Unsubscribed'), ('spam', 'Spam Complaint')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('invitation_id', models.PositiveIntegerField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.marketingcampaign')),
            ],
            options={
                'db_table': 'mail_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='mail_logs_created_4d5c50_idx'), models.Index(fields=['status'], name='mail_logs_status_b63489_idx'), models.Index(fields=['to_email'], name='mail_logs_to_emai_b492ff_idx')],
            },
        ),
    ]
