# Generated by Django 5.0.14 on 2026-07-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_remove_smtpsettings_google_oauth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailbranding',
            options={'verbose_name': 'Email branding', 'verbose_name_plural': 'Email Branding'},
        ),
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email log', 'verbose_name_plural': 'Email logs'},
        ),
        migrations.AlterModelOptions(
            name='emailqueue',
            options={'ordering': ['priority', 'scheduled_for'], 'verbose_name': 'Email queue', 'verbose_name_plural': 'Email queues'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Email template', 'verbose_name_plural': 'Email templates'},
        ),
        migrations.AlterModelOptions(
            name='marketingcampaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'Marketing campaign', 'verbose_name_plural': 'Marketing campaigns'},
        ),
        migrations.AlterModelOptions(
            name='smtpsettings',
            options={'verbose_name': 'SMTP settings', 'verbose_name_plural': 'SMTP Settings'},
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='category',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('welcome', 'Welcome / Registration'), ('verification', 'Email Verification'), ('acceptance', 'Invitation Accepted'), ('marketing', 'Marketing'), ('transactional', 'Transactional'), ('billing', 'Billing & Subscriptions'), ('custom', 'Custom')], default='custom', max_length=30),
        ),
    ]
