# Generated by Django 5.0.14 on 2026-03-19 16:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('work_description', models.TextField(help_text='Description of work done today')),
                ('progress_notes', models.TextField(blank=True)),
                ('progress_photos', models.JSONField(blank=True, default=list)),
                ('weather', models.CharField(blank=True, max_length=100)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_expenses_description', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_comments', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_logs', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'construction_daily_logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(help_text='e.g., Excavator, Mixer, Crane', max_length=100)),
                ('ownership_type', models.CharField(choices=[('owned', 'Owned'), ('rented', 'Rented')], max_length=20)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase cost if owned', max_digits=12, null=True)),
                ('rental_cost_per_day', models.DecimalField(blank=True, decimal_places=2, help_text='Daily rental cost if rented', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='available', max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'construction_equipment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=500)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('allocated_budget', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('start_date', models.DateField()),
                ('estimated_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_sites', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(help_text='Warehouse/storage location for this site', on_delete=django.db.models.deletion.PROTECT, related_name='construction_sites', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'construction_sites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit at time of consumption', max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='quantity * unit_cost', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='construction.dailylog')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='construction_consumptions', to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='construction.site')),
            ],
            options={
                'db_table': 'construction_material_consumption',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('hours_used', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cost', models.DecimalField(decimal_places=2, help_text='Calculated cost for this usage', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('daily_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_usage_logs', to='construction.dailylog')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='construction.equipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_usage_logs', to='construction.site')),
            ],
            options={
                'db_table': 'construction_equipment_usage',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='assigned_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='construction.site'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='construction.site'),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('mason', 'Mason'), ('laborer', 'Laborer'), ('carpenter', 'Carpenter'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('engineer', 'Engineer'), ('supervisor', 'Supervisor'), ('helper', 'Helper'), ('other', 'Other')], max_length=20)),
                ('daily_wage', models.DecimalField(decimal_places=2, help_text='Daily wage rate in NPR', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('id_number', models.CharField(blank=True, help_text='Citizenship/ID number', max_length=50)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('assigned_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='construction.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'construction_workers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('overtime', 'Overtime')], max_length=20)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('wage_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated wage for this attendance', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='construction.site')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='construction.worker')),
            ],
            options={
                'db_table': 'construction_attendance',
                'ordering': ['-date', 'worker__name'],
            },
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['tenant', 'status'], name='constructio_tenant__ac32a3_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['tenant', 'manager'], name='constructio_tenant__3c2787_idx'),
        ),
        migrations.AddIndex(
            model_name='materialconsumption',
            index=models.Index(fields=['tenant', 'site'], name='constructio_tenant__77e667_idx'),
        ),
        migrations.AddIndex(
            model_name='materialconsumption',
            index=models.Index(fields=['tenant', 'daily_log'], name='constructio_tenant__b9cdc6_idx'),
        ),
        migrations.AddIndex(
            model_name='materialconsumption',
            index=models.Index(fields=['tenant', 'product'], name='constructio_tenant__9c0869_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentusagelog',
            index=models.Index(fields=['tenant', 'site', 'date'], name='constructio_tenant__43e814_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentusagelog',
            index=models.Index(fields=['tenant', 'equipment', 'date'], name='constructio_tenant__6b0667_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['tenant', 'status'], name='constructio_tenant__1e21a0_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['tenant', 'assigned_site'], name='constructio_tenant__c32dcb_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylog',
            index=models.Index(fields=['tenant', 'site', 'date'], name='constructio_tenant__093844_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('tenant', 'site', 'date')},
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['tenant', 'status'], name='constructio_tenant__f9c093_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['tenant', 'assigned_site'], name='constructio_tenant__2487b5_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['tenant', 'site', 'date'], name='constructio_tenant__26d60d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['tenant', 'worker', 'date'], name='constructio_tenant__7599ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('tenant', 'worker', 'site', 'date')},
        ),
    ]
