# Generated by Django 5.0.14 on 2026-03-24 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
        ('tenants', '0003_tenant_created_from_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_attendance_set', to='tenants.tenant'),
        ),
    ]
