# Generated by Django 5.0.14 on 2026-03-28 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_alter_attendance_tenant'),
        ('hr', '0004_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='manager',
            field=models.ForeignKey(help_text='Employee assigned as site manager', on_delete=django.db.models.deletion.PROTECT, related_name='managed_sites', to='hr.employee'),
        ),
    ]
