# Generated by Django 5.0.14 on 2026-03-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_alter_site_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='category',
            field=models.CharField(choices=[('mason', 'Mason'), ('laborer', 'Laborer'), ('carpenter', 'Carpenter'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('engineer', 'Engineer'), ('supervisor', 'Supervisor'), ('helper', 'Helper'), ('painter', 'Painter'), ('welder', 'Welder'), ('driver', 'Driver'), ('operator', 'Equipment Operator'), ('other', 'Other')], max_length=20),
        ),
    ]
