# Generated by Django 5.0.14 on 2026-03-28 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_alter_worker_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialconsumption',
            name='daily_log',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to daily log if consumed as part of daily reporting', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='construction.dailylog'),
        ),
    ]
