# Generated by Django 5.0.1 on 2026-08-26 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_alter_materialconsumption_daily_log'),
        ('hr', '0004_payroll'),
        ('inventory', '0009_make_sku_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Employee assigned as site manager', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_sites', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='site',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse/storage location for this site', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='construction_sites', to='inventory.warehouse'),
        ),
    ]
