# Generated by Django 5.0.14 on 2026-03-19 16:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Assets', 'Assets'), ('Liabilities', 'Liabilities'), ('Equity', 'Equity'), ('Income', 'Income'), ('Expense', 'Expense')], max_length=20)),
                ('sub_type', models.CharField(choices=[('Header', 'Header'), ('Current Asset', 'Current Asset'), ('Fixed Asset', 'Fixed Asset'), ('Cash', 'Cash'), ('Bank', 'Bank'), ('Receivable', 'Receivable'), ('Current Liability', 'Current Liability'), ('Long-term Liability', 'Long-term Liability'), ('Payable', 'Payable'), ('Tax', 'Tax'), ('Capital', 'Capital'), ('Retained Earnings', 'Retained Earnings'), ('Revenue', 'Revenue'), ('Other Income', 'Other Income'), ('COGS', 'COGS'), ('Operating', 'Operating')], max_length=50)),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'accounting_accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Current', 'Current Account'), ('Savings', 'Savings Account'), ('Fixed', 'Fixed Deposit'), ('Overdraft', 'Overdraft')], max_length=20)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('last_reconciled', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', max_length=10)),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='accounting.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'accounting_bank_accounts',
                'ordering': ['bank_name', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Manual', 'Manual'), ('Sales', 'Sales'), ('Purchase', 'Purchase'), ('Payment', 'Payment'), ('Receipt', 'Receipt'), ('Adjustment', 'Adjustment')], default='Manual', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=10)),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('reversed_date', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_entries', to=settings.AUTH_USER_MODEL)),
                ('reversal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='original_entry', to='accounting.journalentry')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_entries', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'accounting_journal_entries',
                'ordering': ['-date', '-entry_number'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Opening', 'Opening Balance'), ('Credit', 'Credit'), ('Debit', 'Debit'), ('Transfer', 'Transfer')], max_length=20)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reconciled', models.BooleanField(default=False)),
                ('reconciled_date', models.DateField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.bankaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='accounting.journalentry')),
            ],
            options={
                'db_table': 'accounting_bank_transactions',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'accounting_journal_lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('VAT', 'Value Added Tax'), ('TDS', 'Tax Deducted at Source'), ('Income Tax', 'Income Tax'), ('Other', 'Other')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('applicable_on', models.CharField(choices=[('Sales', 'Sales'), ('Purchase', 'Purchase'), ('Both', 'Both')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_rules', to='accounting.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'accounting_tax_rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VATReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('period', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('output_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('input_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed'), ('paid', 'Paid')], default='draft', max_length=10)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'accounting_vat_returns',
                'ordering': ['-from_date'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['tenant', 'type'], name='accounting__tenant__dd03b4_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['tenant', 'status'], name='accounting__tenant__8bfc06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['tenant', 'status'], name='accounting__tenant__8943d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('tenant', 'account_number')},
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'date'], name='accounting__tenant__a8f2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'status'], name='accounting__tenant__634dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'type'], name='accounting__tenant__dbdf4b_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['tenant', 'bank_account', 'date'], name='accounting__tenant__3f5fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['tenant', 'reconciled'], name='accounting__tenant__24f4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['tenant', 'account'], name='accounting__tenant__a1a834_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['tenant', 'journal_entry'], name='accounting__tenant__76a163_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrule',
            index=models.Index(fields=['tenant', 'status'], name='accounting__tenant__b19dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrule',
            index=models.Index(fields=['tenant', 'type'], name='accounting__tenant__e74156_idx'),
        ),
        migrations.AddIndex(
            model_name='vatreturn',
            index=models.Index(fields=['tenant', 'status'], name='accounting__tenant__43cf6d_idx'),
        ),
        migrations.AddIndex(
            model_name='vatreturn',
            index=models.Index(fields=['tenant', 'from_date', 'to_date'], name='accounting__tenant__6b06f7_idx'),
        ),
    ]
