# Generated by Django 5.0.14 on 2026-07-15 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_fiscal_year_and_tenant_numbers'),
        ('tenants', '0015_rename_organizatio_invited_8f2a1c_idx_organizatio_invited_f28a67_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sub_type',
            field=models.CharField(choices=[('Header', 'Header'), ('Current Asset', 'Current Asset'), ('Fixed Asset', 'Fixed Asset'), ('Cash', 'Cash'), ('Bank', 'Bank'), ('Receivable', 'Receivable'), ('Current Liability', 'Current Liability'), ('Long-term Liability', 'Long-term Liability'), ('Payable', 'Payable'), ('Tax', 'Tax'), ('Capital', 'Capital'), ('Retained Earnings', 'Retained Earnings'), ('Revenue', 'Revenue'), ('Other Income', 'Other Income'), ('COGS', 'COGS'), ('Operating', 'Operating'), ('Administrative', 'Administrative'), ('Other Expense', 'Other Expense'), ('Other Asset', 'Other Asset'), ('Drawing', 'Drawing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
    ]
