# Generated by Django 5.0.14 on 2026-08-31 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_separate_payroll_and_vat_liabilities'),
        ('tenants', '0018_alter_tenant_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g., Cash, Visa Card, eSewa, Cheque - NIC Asia', max_length=100)),
                ('method_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('digital_wallet', 'Digital Wallet'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_default', models.BooleanField(default=False, help_text='System default payment methods cannot be deleted, only deactivated')),
                ('linked_account', models.ForeignKey(help_text='GL account to debit/credit when this payment method is used', on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='accounting.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'accounting_payment_methods',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='accounting__tenant__8f40a4_idx'), models.Index(fields=['tenant', 'method_type'], name='accounting__tenant__8dfdcb_idx')],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
