# Generated by Django 5.0.14 on 2026-09-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_add_payment_method_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='Payment QR code for this bank account (Bank QR / Fonepay QR / Mobile Wallet QR)', null=True, upload_to='bank_qr_codes/'),
        ),
    ]
