# Generated by Django 5.0.14 on 2026-09-01 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_bankaccount_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='accounting.account'),
        ),
    ]
