# Generated by Django 5.0.14 on 2026-09-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_make_gl_account_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='esewa_enabled',
            field=models.BooleanField(default=False, help_text='Accept eSewa payments via this bank account'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='esewa_number',
            field=models.CharField(blank=True, help_text='eSewa ID/number linked to this bank account', max_length=50),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='esewa_qr',
            field=models.ImageField(blank=True, help_text='eSewa QR code for this bank account', null=True, upload_to='bank_qr_codes/esewa/'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='fonepay_enabled',
            field=models.BooleanField(default=False, help_text='Accept FonePay payments via this bank account'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='fonepay_number',
            field=models.CharField(blank=True, help_text='FonePay ID/number linked to this bank account', max_length=50),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='fonepay_qr',
            field=models.ImageField(blank=True, help_text='FonePay QR code for this bank account', null=True, upload_to='bank_qr_codes/fonepay/'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='khalti_enabled',
            field=models.BooleanField(default=False, help_text='Accept Khalti payments via this bank account'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='khalti_number',
            field=models.CharField(blank=True, help_text='Khalti ID/number linked to this bank account', max_length=50),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='khalti_qr',
            field=models.ImageField(blank=True, help_text='Khalti QR code for this bank account', null=True, upload_to='bank_qr_codes/khalti/'),
        ),
    ]
