# Generated by Django 5.0.14 on 2026-03-19 17:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current outstanding balance (credit owed by customer)', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('sale', 'Credit Sale'), ('payment', 'Payment Received'), ('return', 'Sales Return'), ('adjustment', 'Adjustment')], max_length=20)),
                ('reference_type', models.CharField(help_text='e.g., Invoice, Payment, CreditNote', max_length=50)),
                ('reference_number', models.CharField(help_text='Document number', max_length=100)),
                ('reference_id', models.IntegerField(blank=True, help_text='Document ID', null=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount customer owes (increases balance)', max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount customer paid (decreases balance)', max_digits=12)),
                ('running_balance', models.DecimalField(decimal_places=2, help_text='Customer balance after this transaction', max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='sales.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_customer_ledger',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'customer', 'date'], name='sales_custo_tenant__928303_idx'), models.Index(fields=['tenant', 'transaction_type'], name='sales_custo_tenant__c3a1b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('fonepay', 'FonePay'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction ID, Cheque number, etc.', max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to='sales.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales.invoice')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_payments_received',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'customer', 'date'], name='sales_payme_tenant__fbf2ab_idx'), models.Index(fields=['tenant', 'payment_method'], name='sales_payme_tenant__aa5683_idx')],
            },
        ),
    ]
