# Generated by Django 5.0.14 on 2026-03-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_customer_current_balance_invoice_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], default='cash', max_length=20),
        ),
    ]
