# Generated by Django 5.0.14 on 2026-03-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rename_amount_quotation_discount_quotation_subtotal_and_more'),
        ('tenants', '0002_tenant_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('tenant', 'quotation_number')},
        ),
    ]
