# Generated by Django 5.0.14 on 2026-03-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_fix_quotation_number_unique_constraint'),
        ('tenants', '0002_tenant_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='salesorder',
            unique_together={('tenant', 'order_number')},
        ),
    ]
