# Generated by Django 5.0.14 on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_salesorder_order_number_and_more'),
        ('tenants', '0002_tenant_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceived',
            name='payment_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='paymentreceived',
            unique_together={('tenant', 'payment_number')},
        ),
    ]
