# Generated by Django 5.0.14 on 2026-08-21 13:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_invoice_creditnote_tenant_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='credit_note_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='sales.invoice'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('credit', 'Credit')], default='cash', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Draft', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('credit', 'Credit')], default='cash', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='tax_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=13, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
