# Generated by Django 5.0.14 on 2026-08-31 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_add_payment_method_model'),
        ('sales', '0009_make_fields_optional_for_kirana'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceived',
            name='payment_method_ref',
            field=models.ForeignKey(blank=True, help_text='Reference to configured PaymentMethod (preferred over CharField)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_received', to='accounting.paymentmethod'),
        ),
    ]
